apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: invidious-ingress
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`invidious.durp.info`) && PathPrefix(`/`)
    middlewares:
    - name: whitelist
      namespace: traefik
    kind: Rule
    services:
    - name: invidious-invidious
      port: 3000
  tls:
    secretName: invidious-tls

---

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: invidious-tls
spec:
  secretName: invidious-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "invidious.durp.info"
  dnsNames:
  - "invidious.durp.info"  