apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: portainer-ingress
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`portainer.durp.info`) && PathPrefix(`/`)
      kind: Rule
      services:
        - name: portainer
          port: 9443
  tls:
    secretName: portainer-tls

---

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: portainer-tls
spec:
  secretName: portainer-tls
  issuerRef:
    name: vault-issuer
    kind: ClusterIssuer
  commonName: "portainer.internal.durp.info"
  dnsNames:
    - "portainer.internal.durp.info"
