apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: prod-kubeconfig
spec:
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: prod-kubeconfig
  data:
    - secretKey: kubeconfig
      remoteRef:
        key: kv/argocd/prd
        property: kubeconfig

---
apiVersion: cluster.argocd.crossplane.io/v1alpha1
kind: Cluster
metadata:
  name: prd-cluster
  labels:
    purpose: prd
spec:
  forProvider:
    name: prd-cluster
    config:
      kubeconfigSecretRef:
        name: prod-kubeconfig
        key: kubeconfig
  providerConfigRef:
    name: argocd-provider
    namespace: crossplane
