#apiVersion: v1
#kind: Secret
#metadata:
#  name: {{ include "common.names.fullname" . }}-config
#  labels:
#    {{- include "common.labels" . | nindent 4 }}
#data:
#  settings.yml: {{ .Values.searxng.config | toYaml | b64enc | quote }}
#